<?xml version="1.0" encoding="utf-8"?><Database Name="PrivateFinancies" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=PrivateFinancies;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="PrivateFinancies.Properties.Settings" SettingsPropertyName="PrivateFinanciesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Items" Member="Item">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFolder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Item" Member="Item1" ThisKey="Id" OtherKey="Parent" Type="Item" />
      <Association Name="Item_Item" Member="Items1" ThisKey="Parent" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currencies" Member="Currency">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameShort" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NameFull" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsMain" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Accounts" Member="Account" ThisKey="Id" OtherKey="Currency" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Accounts" Member="Account">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFolder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Accounts_Accounts" Member="Account1" ThisKey="Id" OtherKey="Parent" Type="Account" />
      <Association Name="Accounts_Accounts" Member="Accounts1" ThisKey="Parent" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="Currency_Accounts" Member="Currency1" ThisKey="Currency" OtherKey="Id" Type="Currency" IsForeignKey="true" />
    </Type>
  </Table>
</Database>